#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

# Backup original hosts file
sudo cp /etc/hosts ~/hosts.new

# Modify hosts file using sed
sed -i 's/^127.0.0.1.*$/127.0.0.2 localhost/g' ~/hosts.new
sed -i 's/^.*facebook.com.*$/8.8.8.8 facebook.com/g' ~/hosts.new

# Copy modified hosts file back to /etc/hosts
sudo cp -f ~/hosts.new /etc/hosts
